import { languageReducer } from "@/redux/slices";
import { Filter } from "bad-words";
import { time } from "console";
import { create } from "domain";
import { icon } from "leaflet";
import { register } from "module";
import { title } from "process";
import { use } from "react";

// constants/Languages.ts
export const translations = {
  es: {
    home: "Inicio",
    profile: "Perfil",
    vision: "Visión",
    mision: "Misión",
    welcome: "Hola, ",
    select_lang: "Seleccionar Idioma",
    
    tabs: {
      home: "Inicio",
      services: "Servicios",
      jobs: "Trabajos",
      logout: "Cerrar Sesión"
    },

    headertab: {
      appearance: "Apariencia",
      languaje: "Idioma",
      rol:"Rol Asignado",
      rolUser: "Usuario",
      labelpersonal: "Información Personal",
      email: "Correo electrónico",
      name: "Nombre",
      lastName: "Apellido",
      labelPassword: "Contraseña Inicial",
      phone: "Teléfono",
      zipCode: "Código Postal",
      birth: "Fecha de Nacimiento",
      notification: "Notificaciones",
      labelnotification: "No tienes notificaciones nuevas"
    },

    genericbtn: {
      likebtn: "Me gusta",
      dislikebtn: "No me gusta",
      savebtn: "Guardar",
      sharingbtn: "Compartir",
      viewdetail: "Ver detalle",
      contactme: "Contactar",
      resultone: "Resultado encontrado",
      resultdomore: "Resultados encontrados",
      viewallresults: "Ver todos los resultados",
      photo:"Foto",
      choisephoto:"Seleccionar fotografía",
      sendsuggestion: "Enviar Sugerencia",
      tittleReview: "Revisión",   
      aprovedbtn: "Aprobar",
      rejectbtn: "Rechazar",
      reviews: "Reseñas",
      serverError: "Error en servidor",
      callbton: "Llamada",
      call: "Llamar",
      email: "Correo",
      web: " Web",
      route: "Ruta",
      sendrequest:"Enviar Solicitud",
      verify:"Verificar",
      viewall: "Ver todos",
      results: "resultados",

      
    },
    genericlabel:{
      labelopinion:"Escribe tu opinión...",
      labelsendreq: "Solicitud Enviada",
      labelerrorsend:"Error al enviar la solicitud.",
      labelerrorserver:"Error en servidor",
      labelerrorconection:"No se pudo conectar al servidor.",
      labelmessajeaprov:"El contacto ha sido aprobado exitosamente por",
      labelaprov:"Aprobado",
      labelmonth:"mes(es).",
      labelaproval:"No se pudo aprobar.",
      labelreject:"Rechazado",
      labeldeletecontac:"Contacto eliminado.",
      labelnoreject: "No se pudo rechazar.",
      labelaprovaladmin:"Pendiente de aprobación (Admin)",
      labelviewdetail:"Ver detalle",
      labelme:" mi",
      lableplan:"Plan ",
      labelaprovedplan:"Aprobar Plan",
      labelexperien:"Experiencias y Opiniones",
      labelshareexper:"Compartir experiencia",
      labelreviewthanks:"¡Gracias!",
      labelreviewexp:"Tu reseña ha sido publicada exitosamente.",
      labeljoinred:"Unirse a la Red",
      labelcatergory:"Categoría",   
      labelnameprof: "Nombre del Profesional / Mentor",
      labelcityaddres:"Ciudad o Dirección",
      labelzipcde:"Código Postal",
      lablelespecia:"Especialidad o cómo ayudas...",
      labelphonecont:"Teléfono de Contacto",
      labelcheckpay:"Verificación de Pago",
      labelmessagepay:"Para promocionar tu perfil de apoyo, realiza el pago de {amount} mediante Zelle y escribe el código de confirmación aquí abajo.",
      labelconfirmpay:"# CONFIRMACION DE ",
      labelcategorys:"Categorías",
      labelinapro:"Comentario inapropiado",
      labelfields:"Debes completar todos los campos obligatorios.",
      labelcontacsupp:"Te recomiendo este contacto de apoyo",
      labelerrorsave:"Error ocurrido guardando",
      labelerrorimage:"Error subiendo imagen",
      labelerrorimageinapro:"Imagen inválida o inapropiada",
      labelcodepostal:"Código postal...",

    },
    categoryplan: {
      coupon: "Cupón",
      basic: "Básico",
      premium: "Premium",
      unlimited: "Ilimitado",
      coupondesc: "Cupón o periodo de prueba.",
      basicdesc: "Ideal para profesionales independientes.",
      premiumdesc: "Mayor visibilidad en los resultados.",
      unlimiteddesc: "Prioridad máxima y soporte VIP.",
    },
    hometab: {
        registerhome: "Regístrarme",
        acces: "Ingresar",
        login: "Iniciar Sesión",
        register: "Regístrate aquí",
        haveaccount: "¿Ya tienes cuenta?  ",
        nohaveaccount: "¿No tienes cuenta?  ",
        dateBirthday: "Fecha de nacimiento",
        username: "Usuario:",
        password: "Contraseña:",
        googleacount: "Continuar con Google",
        mission: "Nuestra Misión",
        ready: "Listo",   
        missiondesc: "Crear comunidades más unidas, participativas y solidarias, donde cada residente se sienta conectado, seguro y orgulloso de su barrio.",
        vision: "Nuestra Visión",
        visiondesc: "Fortalecer las economías locales conectando a los residentes con los comercios y servicios de su barrio, promoviendo el consumo local y facilitando un ecosistema de intercambio y colaboración."
    },
    servicestab:{
      service1: "Abogados",
      icon1: "scale-balance",
      service2: "Comunidad",
      icon2: "account-group-outline",
      service3: "Donaciones",
      icon3: "hand-heart",
      service4: "Eventos",
      icon4: "calendar-clock",
      service5: "Tiendas",
      icon5: "shopping-search",
      service6: "Emprendimientos",
      icon6: "lightbulb-multiple-outline",
      help_question: "¿En qué podemos ayudarte hoy?",
      service_support: "Red de Apoyo",
      service7: "Red de Apoyo",
      icon7: "heart-pulse",
      welcome_user: "¡Bienvenido, Cesar!"
    },
    lawyerstab: {
      labelawyer: "Abogad(@) ",
      label: "Especialidades",
      practiceAreas: ['Todas', 'General', 'Inmigración', 'Familia', 'Accidentes', 'Laboral', 'Criminal', 'Pro Bono', 'Civil', 'Bienes Raíces'],
      //practiceAreas: "all",
      messagezip: "Código Postal",
      validatezip: "Código Postal no encontrado.",
      viewallresults: "Ver todos los resultados",
      zipnofound:"ZIP no encontrado.",
      noReviews: "Aún no hay reseñas.", // <--- Agrega esta
      addReview: "Danos tu opinión",    // <--- Agrega esta
      placeholderReview: "Escribe tu experiencia...", // <--- Agrega esta
      publishBtn: "Publicar reseña" ,     // <--- Agrega esta
      typeReview: "Escribir mi opinión",
      experience:"¿Cómo fue tu experiencia?",
      backBtn: "Volver",
      recent: "Reciente",
      reviews: "Reseñas",
      route: "Ruta",
      call: "Llamar",
      messageNoemptytitle: "Descubre Abogados",
      messageNoempty: "Ingresa un código postal de 5 dígitos para encontrar profesionales en tu área.",
      messageNodatatitle: "No hay abogados",
      messageNodata: "¡Sé el primero en sugerir un abogado para esta zona!",
      ///sugeridos
      suggest: "Sugerir Abogado",
      writeOpinionPlaceholder: "Escribe tu opinión...",
      noticeTitle: "Aviso",
      alreadyReviewed: "Ya has escrito una reseña para este abogado.",
      expiredWarning: "Suscripción vencida. El público no puede verlo.",
      renewBtn: "Renovar",
      renewTitle: "Renovar Perfil",
      renewDescPrefix: "Re-activa el perfil de ",
      renewDescSuffix: " enviando el comprobante de tu nuevo pago de renovación mensual.",
      sendRenewBtn: "Enviar Renovación",
      paymentVerification: "Verificación de Pago",
      paymentInstructions: "Para publicar tu perfil, realiza el pago de $50 USD mediante Zelle o Venmo y escribe el código de confirmación aquí abajo.",
      noLawyersFound: "No se encontraron abogados aquí.",
      newLabel: "Nuevo",
      aboutTitle: "Acerca de",
      thanksTitle: "¡Gracias!",
      reviewSuccessMsg: "Tu reseña ha sido publicada exitosamente.",
      serverConnectionError: "No se pudo conectar al servidor.",
      enterRefCode: "Ingresa el código de confirmación de pago.",
      successTitle: "Éxito",
      renewSuccessMsg: "Tu renovación fue enviada y se encuentra pendiente de revisión del administrador.",
      renewErrorMsg: "No se pudo enviar la renovación o el código ya fue utilizado.",
      approvedTitle: "Aprobado",
      approvedMsgPrefix: "El perfil es público por ",
      approvedMsgSuffix: " mes(es).",
      rejectedTitle: "Rechazado",
      rejectedMsg: "Perfil eliminado.",
      writingreview:"Escribir reseña",
      commutnityopini: "Opiniones",
      errorTitle: "Error",
      alertmessage: "Completar campos obligatorios incluyendo pago",
      sendnewsug: "Enviado con éxito, pendiente de revisión de pago",
      approveError:"No se pudo aprobar.",
      rejectError:"No se pudo rechazar.",
      placeHoldname: "Nombre",
      placeHoldAddress: "Dirección",
      description: "Descripción"
    },
    communitytab: {
      label: "Comunidad ",
      labeltypepost: "Tipo de publicación",
      typepost : ['Todos', 'Experiencia', 'Pregunta', 'Consejo'],
      typepostAdd : ['Experiencia', 'Pregunta', 'Consejo'],
      messagenewpost: "Nueva publicación",
      closepost: "Cerrar",
      botonpost: "Publicar",
      firtscomment: "Sé el primero en comentar",
      questionnewpost: '¿Qué quieres compartir?',
      textInappropriateTittle: "Contenido inapropiado",
      textInappropriateDescription: "Tu mensaje contiene palabras no permitidas. Por favor, mantén un lenguaje respetuoso.",
      imageInappropriateTittle: "Imagen rechazada",
      imageInappropriateDescription: "Nuestra IA detectó contenido sensible. Por favor elige otra imagen.",
      publishedPostLabel: "¡Éxito!",
      publishedPostDescription: "Tu post ha sido publicado.",
      errorServer: "No se pudo conectar con el servidor de moderación.",
      category: "Categoría",
      subCategories: ['General','Comida','Trabajo','Trámites','Salud','Nuevos'],
      filter:"Filtrar",
      placeHolderModal: "Escribe algo...",
      sendbutton: "Enviar",
      responsebutton: "Responder",
      messageNewPost:"¿Qué estás pensando?",
      messageemptytitle: "Descubre tu zona",
      messageempty: "Ingresa un código postal de 5 dígitos para conectar con la comunidad local.",
      messageNodatatitle: "No hay publicaciones",
      messageNodata: "¡Sé el primero en sugerir un abogado para esta zona!"
    },
    donationstab: {
        label: "Donación ",
        category: "Categorías",
        placeholInput: "¿Qué buscas hoy?",
        subCategories: ['Todas','Ropa','Alimentos','Muebles','Electrónica','Otros'],
        messageMessageDonation: "Nueva donación",
        messageDonation: "¿Qué te gustaría donar o necesitas?",
        closeDonation: "Cerrar",
        botonDonation: "Publicar",
        statusBottonModalDis: "Disponibles",
        statusBottonModalDel: "Entregados",
        statusDonatioAct: "Entregado",
        statusDonatioReact: "Reactiva",
        newdonnationTittle: "Titulo de la donación",
        newdonnationdescription: "Describe brevemente el estado",
        textInappropriateTittle: "Contenido inapropiado",
        textInappropriateDescription: "Tu mensaje contiene palabras no permitidas. Por favor, mantén un lenguaje respetuoso.",
        imageInappropriateTittle: "Imagen rechazada",
        imageInappropriateDescription: "Nuestra IA detectó contenido sensible. Por favor elige otra imagen.",
        publishedDonationLabel: "¡Éxito!",
        publishedDonationDescription: "Tu publicación ha sido publicada.",
        errorServer: "No se pudo conectar con el servidor de moderación.",
        sendbutton: "Enviar",
        messagenotdonnations:"No se encontraron donaciones disponibles.",
        choisephoto:"Seleccionar fotografía",
        callbton: "Llamada",
        typeContact: "Método de contacto",
        numberContact: "Número de contacto",
        savebutton: "Guardar",
        deliverBtn: "Entregar",
        activateBtn: "Activar"
    },
    eventstab: {
        label: "Eventos ",
        filter: "Filtros",
        inputEvents:"Buscar eventos...",
        botonEvent: "Publicar evento",
        photoEvent :"Foto del evento",
        typeEvent: "Tipo de evento",
        dateEvent: "Fecha del evento",
        timeEvent: "Horario (Inicio - Fin)",
        readyBtn: "Listo",
        nameEvent: "Nombre del evento",
        addressEvent: "Dirección del evento",
        detailsEvent: "Detalles del evento",
        sharringEvent: "Compartir evento",
        createEvent: "Crear evento",
        call : "Llamada",
        informationevent: "Información del evento",
        typeContact: "Método de contacto",
        categoriesList: ["Todos", "Social", "Salud", "Educación", "Deportes"] 
    },
    storestab:{
      label: "Tiendas ",
      categoriesList: ['Todas', 'Supermercado', 'Panadería', 'Electrónica', 'Otros'],
      sharemessage: "Mira este establecimiento en ViviendoEnUSA",
      alertmessage: "Atención, Todos los campos son obligatorios.",
      sendnewsug: "¡Enviado!, Tu sugerencia será revisada.",
      reviews: "Reseñas",
      route: "Ruta",
      callbton: "Llamada",
      commutnityopini:"Opiniones de la Comunidad",
      writingreview:"Escribir reseña",
      textphoto:"Foto del local",
      category: "Categoría",
      placeHoldname:"Nombre comercial",
      placeHoldAddress: "Dirección física",
      messagezip: "Código Postal",
      description: "Descripción",
      phoneContacto: "Teléfono de contacto",
      sendbutton: "Guardar",
      verify: "Revisión"

    },
    entrepreneurshiptab:{
        label: "Emprendimientos ",
        searchentrepre:"Buscar emprendimientos...",
        backBtn: "Volver",
        viewdetail: "Ver detalle",
        viewExpe:"Tu experiencia",
        viewcategory: "Categorías",
        nofoundresults: "No hay resultados",
        aboutBussines: "Sobre el negocio",
        businesshelpful: "¿Te fue útil este negocio?",
        reviews: "Reseñas",
        writing : "Escribir", 
        viewAllreviews: "Ver todas las reseñas...",
        communityopinions: "Opiniones de la comunidad",
        writingReviews: "Escribir reseña",
        whitoutReviews: "Aún no hay reseñas. ¡Sé el primero!",
        newentrepreneurship: "Nuevo emprendimiento",
        businessphoto: "Foto del negocio",
        contactMethod: "Método de contacto principal",
        call : "Llamada",
        promotion: "Promoción (opcional)",
        publishEntrepre: "Publicar Emprendimiento",
        publishReviews:"Publicar reseña",
        exampleoffet: "Ej: 10% OFF en primera consulta",
        descripservicesplace: "Descripción de tus servicios...",
        namebussinesplac: "Nombre del negocio",
        categoryentre: ['Todas', 'Venta de garaje', 'Reparaciones', 'Comida', 'Salud', 'Tecnología'],
        viewopinion: "Escribe tu opinión...",
        categoryentreicon: {
          'Todas':'apps',
          'Venta de garaje':'sale',
          'Reparaciones':'wrench-outline',
          'Comida':'silverware-fork-knife', 
          'Salud':'heart-pulse', 
          'Tecnología':'laptop'
          }
    },jobstab:{
      label: "Empleos ",
      labeljobs: "Publicar Empleo",
      labeladmin: "* Requiere revisión de administrador",
      statusBottonModalDis: "Disponibles",
      statusBottonModalNoDis: "No disponibles",
      filter: "Filtros",
      jobtitles:{
        'Bodega': ['Forklift Operator', 'Empacador (Packer)', 'Recibidor', 'Material Handler', 'Lider de Bodega'], 
        'Construcción': ['Carpintero', 'Electricista', 'Plomero', 'Ayudante'],
        'Limpieza': ['Housekeeper', 'Limpieza Comercial', 'Janitor'],
        'Restaurantes': ['Cocinero', 'Mesero/a', 'Dishwasher', 'Bartender'],
        'Transporte': ['Chofer CDL', 'Repartidor', 'Mecánico'],
        'Tecnología': ['Desarrollador', 'Soporte Técnico', 'Diseñador'],
        'Todos': ['Asistente', 'Servicio al Cliente', 'Ventas']
      },
      jobCategories:[
        { id: 'Todos', icon: 'apps' },
        { id: 'Bodega', icon: 'warehouse' }, 
        { id: 'Construcción', icon: 'hammer-wrench' },
        { id: 'Limpieza', icon: 'broom' },
        { id: 'Restaurantes', icon: 'silverware-fork-knife' },
        { id: 'Transporte', icon: 'truck-fast' },
        { id: 'Tecnología', icon: 'laptop' }
      ],titlejobs: "Título del puesto *",
      state: "Estado *",
      city: "Ciudad *",
      companie: "Compañía *",
      labeljobselec:"Toca para Seleccionar o Registrar...",
      labelvalue:"Pago por hora (USD) *",
      shitfdispooued: "Turnos disponibles *",
      descripcion:"Descripción *",
      labeljobreq:"Requisitos, habilidades necesarias...",
      filterjob: "Filtrar por Puesto",
      alljob: "Todos los puestos",
      filtershift: "Filtrar por Turno",
      allshifts: "Todos los turnos",
      filterlocation: "Filtro de Ubicación",
      selectstate:"1. Selecciona el Estado",
      selectcity:"2. Selecciona las Ciudades",
      allin: "Todas en ",
      aplifilter: "Aplicar Filtros",
      whitoutreview:"Sin reseñas",
      ratigcompanie: "Califica a la empresa",
      labeldescribe:"Describe tu experiencia trabajando aquí...",
      labelanonimous:"Publicar como Anónimo",
      publish:"Publicar",
      cancel:"Cancelar",
      writereview:"Escribir una reseña",
      firtsreview:"Sé el primero en escribir una reseña",
      publishoffert: "Publicar Oferta",
      labelmax:"Máximo (Opcional)",
      labelmin:"Mínimo",
      labelcity:"Seleccionar Ciudad...",
      writejob:"Escribe o elige un puesto arriba...",
      labelpaycomp: "Pagar y Registrar Empresa",
      placehoderreference:"# CONFIRMACIÓN DE ",
      labelregistercomp1:"Para registrar la empresa, realiza el pago de ",
      labelregistercomp2:"mediante Zelle y escribe el código abajo.",
      labeltelcompanie:"Teléfono de la empresa *",
      labelplan :"Selecciona tu plan *",
      labeleamil:"Correo electrónico corporativo...",
      labeltaxid:"TAX ID / EIN (Opcional)",
      namecompanies:"Nombre comercial *",
      registrecompanie: "Registra tu empresa para acceder al plan corporativo y publicar vacantes.",
      registerlabelcomp:"Registrar Empresa",
      nocompanieregister:"No tienes empresas registradas.",
      yourcompanies:"Tus Empresas",
      choisecity:"Elige la Ciudad en",
      viewreviews:"Ver Reseñas",
      descriptionoffert:"Descripción de la Vacante",
      closevacanse:"Cerrar Vacante",
      reopenvacanse:"Reabrir Vacante",
      novacancy:"No hay vacantes disponibles en este momento.",
      vacancyactive:"Vacantes Activas",
      viewall: "Ver todas",
      vacancys: "Vacantes",
      actives: "Activas",
      hadvacan:"Tiene",
      contact:"Contacto:",
      savevacancy: "Aún no has guardado ninguna vacante.",
      findvacancy: "No se encontraron empleos con estos filtros.",
      anycity: "Cualquier Puesto en",

    },supporttab:{
      label: "Red de Apoyo ",
      description: "Encuentra recursos y ayuda en tu comunidad.",
      category: "Categoría",
      subCategories: ['Salud', 'Alimentos', 'Asesoría Legal', 'Apoyo Emocional', 'Otros'],
      contactSupport: "Contactar Red de Apoyo",
      support_btn_title: "Red de Apoyo",
      labelcheck:"Revisaremos la información para agregarla a la Red de Apoyo.",
      phone:"Línea de Crisis 988",
      labelphone:"Atención en español 24/7"
    },
    

    
  },
  en: {
    home: "Home",
    profile: "Profile",
    vision: "Vision",
    mision: "Mission",
    welcome: "Hello, ",
    select_lang: "Select Language",
    tabs: {
      home: "Home",
      services: "Services",
      jobs: "jobs",
      logout: "Close Session"
    },
    headertab: {
      appearance: "Appearance",
      languaje: "Language",
      rol:"Assigned Role",
      rolUser: "User",
      labelpersonal: "Personal Information",
      email: "Email",
      name: "Name",
      lastName: "Last Name",
      labelPassword: "Initial Password",
      phone: "Phone",
      zipCode: "ZIP Code",
      birth: "Birthdate",
      notification: "Notifications",
      labelnotification: "You have no new notifications"
    },
    genericbtn: {
      likebtn: "I like it",
      dislikebtn: "Not for me",
      savebtn: "Save",
      sharingbtn: "Share",
      viewdetail: "View details",
      contactme: "Contact",
      resultone: "Result found",
      resultdomore: "Results found",
      viewallresults: "View all results",
      photo:"Photo",
      choisephoto: "Photo",
      sendsuggestion: "Send Suggestion",
      tittleReview: "Review",
      aprovedbtn: "Approve",
      rejectbtn: "Reject",
      reviews: "Reviews",
      serverError: "Server error",
      callbton: "Call",
      call: "Call",
      email: "Email",
      web: " Web",
      route: "Route",
      sendrequest:"Send Request" ,
      verify:"Verify",
      viewall: "View all",
      results: "results"

      

    },
    genericlabel:{
      labelopinion:"Write your opinion...",
      labelsendreq: "Request Sent",
      labelerrorsend:"Error sending request.",
      labelerrorserver:"Server error",
      labelerrorconection:"No connection to the server.",
      labelmessajeaprov:"The contact has been successfully approved by",
      labelaprov:"Approved",
      labelmonth:"month(s).",
      labelaproval:"Could not be approved.",
      labelreject:"Rejected",
      labeldeletecontac:"Contact deleted.",
      labelnoreject: "Could not be rejected.",
      labelaprovaladmin:"Pending approval (Admin)",
      labelviewdetail:"View details",
      labelme:" my",
      lableplan:"Plan ",
      labelaprovedplan:"Approve Plan",
      labelexperien:"Experiences and Opinions",
      labelshareexper:"Share experience",
      labelreviewthanks:"Thank you!",
      labelreviewexp:"Your review has been successfully published.",
      labeljoinred:"Join the Network",
      labelcatergory:"Category",
      labelnameprof: "Professional / Mentor Name",
      labelcityaddres:"City or Address",
      labelzipcde:"ZIP Code",
      lablelespecia:"Specialty or how you help...",
      labelphonecont:"Contact Phone Number",
      labelcheckpay:"Payment Verification",
      labelmessagepay:"To promote your support profile, make a payment of {amount} via Zelle and write the confirmation code below.",
      labelconfirmpay:"# CONFIRMATION OF ",
      labelcategorys:"Categories",
      labelinapro:"Inappropriate comment",
      labelfields:"You must complete all required fields.",
      labelcontacsupp:"I recommend this support contact",
      labelerrorsave:"Error occurred saving",
      labelerrorimage:"Error uploading image",
      labelerrorimageinapro:"Invalid or inappropriate image",
      labelcodepostal: "ZIP code...",
      
    },
    categoryplan: {
      coupon: "Coupon",
      basic: "Basic",
      premium: "Premium",
      unlimited: "Unlimited",
      coupondesc: "Coupon or trial period.",
      basicdesc: "Ideal for independent professionals.",
      premiumdesc: "Greater visibility in search results.",
      unlimiteddesc: "Maximum priority and VIP support.",
    },
    hometab: {
        registerhome: "Register",
        acces: "Access",
        login: "Login",
        register: "Register here",
        haveaccount: "Already have an account?",  
        nohaveaccount: "Don't have an account?",
        dateBirthday: "Birthdate",
        username: "Username:",
        password: "Password:",
        googleacount: "Continue with Google",
        mission: "Our Mission",  
        ready: "Ready", 
        missiondesc: "Create more united, participative and supportive communities, where every resident feels connected, safe and proud of their neighborhood.",
        vision: "Our Vision",
        visiondesc: "Strengthen local economies by connecting residents with the businesses and services in their neighborhood, promoting local consumption and facilitating an ecosystem of exchange and collaboration."
    },
    servicestab:{
      service1: "Lawyers",
      icon1: "scale-balance",
      service2: "Community",
      icon2: "account-group-outline",
      service3: "Donations",
      icon3: "hand-heart",
      service4: "Events",
      icon4: "calendar-clock",
      service5: "Stores",
      icon5: "shopping-search",
      service6: "Entrepreneurs",
      icon6: "lightbulb-multiple-outline",
      help_question: "How can we help you today?",
      service_support: "Support Net",
      service7: "Support Net",
      icon7: "heart-pulse",
      welcome_user: "Welcome, "
    },
    lawyerstab: {
      labelawyer: "Lawyer ",
      label: "Specialties",
      practiceAreas:  ['All', 'General', 'Immigration', 'Family', 'Accidents', 'Labor', 'Criminal', 'Pro Bono', 'Civil', 'Real Estate'],
      //practiceAreas: "all",
      messagezip: "ZIP Code",
      validatezip: "ZIP not found.",
      zipnofound:"ZIP not found.",
      noReviews: "There are no reviews yet.", // <--- Agrega esta
      addReview: "Give us your opinion",    // <--- Agrega esta
      placeholderReview: "Write about your experience...", // <--- Agrega esta
      publishBtn: "Post review",      // <--- Agrega esta
      typeReview: "Write my review",
      experience:"How was your experience?",
      backBtn: "Go back",
      recent: "Recent",
      reviews: "Reviews",
      route: "Route",
      call: "Call",
      messageNoemptytitle: "Discover Lawyers",
      messageNoempty: "Enter a 5-digit ZIP code to find professionals in your area.",
      messageNodatatitle: "No lawyers found",
      messageNodata: "Be the first to suggest a lawyer for this area!",
      ///
      suggest: "Suggest a Lawyer",
      writeOpinionPlaceholder: "Write your review...",
      noticeTitle: "Notice",
      alreadyReviewed: "You have already written a review for this lawyer.",
      expiredWarning: "Subscription expired. Not visible to the public.",
      renewBtn: "Renew",
      renewTitle: "Renew Profile",
      renewDescPrefix: "Reactivate the profile for ",
      renewDescSuffix: " by submitting proof of your new monthly renewal payment.",
      sendRenewBtn: "Submit Renewal",
      paymentVerification: "Payment Verification",
      paymentInstructions: "To publish your profile, make a payment of $50 USD via Zelle or Venmo and enter the confirmation code below.",
      noLawyersFound: "No lawyers found here.",
      newLabel: "New",
      aboutTitle: "About",
      thanksTitle: "Thank you!",
      reviewSuccessMsg: "Your review has been successfully published.",
      serverConnectionError: "Could not connect to the server.",
      enterRefCode: "Enter the payment confirmation code.",
      successTitle: "Success",
      renewSuccessMsg: "Your renewal has been submitted and is pending administrator review.",
      renewErrorMsg: "Renewal could not be submitted or the code has already been used.",
      approvedTitle: "Approved",
      approvedMsgPrefix: "The profile is public for ",
      approvedMsgSuffix: " month(s).",
      rejectedTitle: "Rejected",
      rejectedMsg: "Profile deleted.",
      writingreview:"Write a review",
      commutnityopini: "Opinions",
      errorTitle: "Error",
      alertmessage: "Complete the required fields, including payment",
      sendnewsug: "Successfully sent, pending payment review",
      approveError:"It could not be approved.",
      rejectError:"It could not be rejected.",
      placeHoldname: "Name",
      placeHoldAddress: "Address",
      description: "Description"


    },
    communitytab: {
      label: "Community ",
      labeltypepost: "Post type",
      typepost : ['All', 'Experience', 'Question', 'Advice'],
      typepostAdd : ['Experience', 'Question', 'Advice'],
      messagenewpost: "New post",
      closepost: "Close",
      botonpost: "Post",
      firtscomment: "Be the first to comment",
      questionnewpost: 'What do you want to share?',
      textInappropriateTittle: "Inappropriate content",
      textInappropriateDescription: "Your post contains forbidden words. Please use respectful language.",
      imageInappropriateTittle: "Image rejected",
      imageInappropriateDescription: "Our AI detected sensitive content. Please choose another image.",
      publishedPostLabel: "Success!",
      publishedPostDescription: "Your post has been published.",
      errorServer: "Could not connect to the moderation server.",
      category: "Category",
      subCategories: ['General','Food','Work','Procedures','Health','New'],
      filter:"Filter",
      placeHolderModal: "Write something...",
      sendbutton: "Send",
      responsebutton: "Reply",
      messageNewPost:"What are you thinking?",
      messageemptytitle: "Discover your area",
      messageempty: "Enter a 5-digit ZIP code to connect with the local community.",
      messageNodatatitle: "No posts found",
      messageNodata: "Be the first to suggest a lawyer for this area!"
    },
    donationstab: {
        label: "Donation ",
        category: "Categories",
        placeholInput: "What are you looking for today?",
        subCategories: ['All','Clothing','Food','Furniture','Electronics','Other'],
        messageMessageDonation: "New donation",
        messageDonation: "What would you like to donate or need?",
        closeDonation: "Close",
        botonDonation: "Post",
        statusBottonModalDis: "Availables",
        statusBottonModalDel: "Delivered",
        statusDonatioAct: "Delivered",
        statusDonatioReact: "Reactivate",
        newdonnationTittle: "Donation title",
        newdonnationdescription: "Briefly describe the condition",
        textInappropriateTittle: "Inappropriate content",
        textInappropriateDescription: "Your post contains forbidden words. Please use respectful language.",
        imageInappropriateTittle: "Image rejected",
        imageInappropriateDescription: "Our AI detected sensitive content. Please choose another image.",
        publishedDonationLabel: "Success!",
        publishedDonationDescription: "Your post has been published.",
        errorServer: "Could not connect to the moderation server.",
        sendbutton: "Send",
        messagenotdonnations:"No available donations found.",
        choisephoto:"Select photo",
        callbton: "Call",
        typeContact: "Contact method",
        numberContact: "Contact number",
        savebutton: "Save",      
        deliverBtn: "Delivered",
        activateBtn: "Activate"
      },
      eventstab: {
        label: "Events",
        filter: "Filters",
        inputEvents:"Search for events...",
        botonEvent: "Post event",
        photoEvent :"Event photo",
        typeEvent: "Event type",
        dateEvent: "Event date",
        timeEvent: "Schedule (Start - End)",
        readyBtn: "Ready",
        nameEvent: "Event name",
        addressEvent: "Event address",
        detailsEvent: "Event details",
        sharringEvent: "Share event",
        createEvent: "Create event",
        call : "Call",
        informationevent: "Event Information",
        typeContact: "Contact method",
        categoriesList: ["All", "Social", "Health", "Education", "Sports"] 
      },
      storestab:{
        label: "Stores ",
        categoriesList: ['All', 'Supermarket', 'Bakery', 'Electronics', 'Other'],
        sharemessage: "Check out this establishment on LivingInUSA",
        alertmessage: "Attention, all fields are required.",
        sendnewsug: "Sent! Your suggestion will be reviewed.",
        reviews: "Reviews",
        route: "Route",
        callbton: "Call",
        commutnityopini:"Community Opinions",
        writingreview:"Write review",
        textphoto:"Photo of the premises",
        category: "Category",
        placeHoldname: "Business Name",
        placeHoldAddress: "Physical Address",
        messagezip: "Postal Code",
        description: "Descripción",
        phoneContacto: "Contact phone number",
        sendbutton: "Save",
        verify: "verify"
      },
    entrepreneurshiptab:{
        label: "Entrepreneurship ",
        searchentrepre:"Search for ventures...",
        backBtn: "Go back",
        viewdetail: "View detail",
        viewExpe:"Your experience",
        viewcategory: "Category",
        nofoundresults: "No found results",
        aboutBussines: "About the business",
        businesshelpful: "Did you find this business helpful?",
        reviews: "Reviews",
        writing : "Writing",
        viewAllreviews: "See all reviews...",
        communityopinions: "Community opinions",
        writingReviews: "Write a review",
        whitoutReviews: "There are no reviews yet. Be the first!",
        newentrepreneurship: "New Entrepreneurship",
        businessphoto: "Business photo",
        contactMethod: "Primary contact method",
        call: "Call",
        promotion: "Promotion (optional)",
        publishEntrepre: "Publish Entrepreneurship",
        publishReviews:"Publish review",
        exampleoffet: "Ex: 10% OFF on the first consultation",
        descripservicesplace: "Description of your services...",
        namebussinesplac: "Business Name",
        categoryentre: ['All', 'Garage Sale', 'Repairs', 'Food', 'Health', 'Technology'],
        viewopinion: "Write your opinion...",
        categoryentreicon: {
          'All':'apps',
          'Garage Sale':'sale',
          'Repairs':'wrench-outline',
          'Food':'silverware-fork-knife', 
          'Health':'heart-pulse', 
          'Technology':'laptop'
          }
        
    },jobstab:{
        label: "Jobs ",
        labeljobs: "Post a Job",
        labeladmin: "* Requires administrator review",
        statusBottonModalDis: "Available",
        statusBottonModalNoDis: "Not available",
        filter: "filters",
        jobtitles: {
          'Warehouse': ['Forklift Operator', 'Packer', 'Receiver', 'Material Handler', 'Warehouse Leader'],
          'Construction': ['Carpenter', 'Electrician', 'Plumber', 'Helper'],
          'Cleaning': ['Housekeeper', 'Commercial Cleaner', 'Janitor'],
          'Restaurants': ['Cook', 'Waiter/Waitress', 'Dishwasher', 'Bartender'],
          'Transportation': ['CDL Driver', 'Delivery Driver', 'Mechanic'],
          'Technology': ['Developer', 'Tech Support', 'Designer'],
          'All': ['Assistant', 'Customer Service', 'Sales']
        },
        jobCategories:[
          {id: 'All', icon: 'apps' },
          {id: 'Warehouse', icon: 'warehouse' },
          {id: 'Construction', icon: 'hammer-wrench' },
          {id: 'Cleaning', icon: 'broom' },
          {id: 'Restaurants', icon: 'silverware-fork-knife' },
          {id: 'Transportation', icon: 'truck-fast' },
          {id: 'Technology', icon: 'laptop' }
          ],
          titlejobs: "Job Title *",
          state: "State *",
          city: "City *",  
          companie: "Company *", 
          labeljobselec:"Tap to Select or Register...",
          labeljobreq:"Requirements, necessary skills...",
          labelvalue:"Hourly Pay (USD) *",
          shitfdispooued: "Available Shifts *",
          descripcion:"Description *",
          filterjob: "Filter by Job Title",
          alljob: "All Job Titles",
          filtershift: "Filter by Shift",
          allshifts: "All Shifts",    
          filterlocation: "Location Filter",
          selectstate:"1. Select State",
          selectcity:"2. Select Cities",
          allin: "All in ",
          aplifilter: "Apply Filters",
          whitoutreview:"Without reviews",
          ratigcompanie: "Rate the company",
          labeldescribe:"Describe your experience working here...",
          labelanonimous:"Post as Anonymous",
          publish:"Post",
          cancel:"Cancel",
          writereview:"Write a review",
          firtsreview:"Be the first to write a review",
          publishoffert: "Post Offer",
          labelmax:"Maximum (Optional)",
          labelmin:"Minimum",
          labelcity:"Select City...",
          writejob:"Write or choose a job title above...",
          labelpaycomp: "Pay and Register Company",
          placehoderreference:"# CONFIRMATION OF ",
          labelregistercomp1:"To register the company, make a payment of ",
          labelregistercomp2:" via Zelle and enter the code below.",
          labeltelcompanie:"Company phone number *",
          labelplan :"Select your plan *",
          labeleamil:"Corporate email...",     
          labeltaxid:"TAX ID / EIN (Optional)", 
          namecompanies:"Comercial Name *",
          registrecompanie: "Register your company to access the corporate plan and post job openings.",
          registerlabelcomp:"Register Company",
          nocompanieregister:"You have no registered companies.",
          yourcompanies:"Your Companies",
          choisecity:"Choose the City in",
          viewreviews:"View Reviews",
          descriptionoffert:"Job Description",
          closevacanse:"Close Vacancy",
          reopenvacanse:"Reopen Vacancy",
          novacancy:"There are no vacancies available at this time.",
          vacancyactive:"Active Vacancies",
          viewall: "View all",
          vacancys: "Vacancies",
          actives: "Active",
          hadvacan:"Has",
          contact:"Contact:",
          savevacancy: "You haven't saved any vacancies yet.",
          findvacancy: "No jobs found with these filters.",
          anycity: "Any Job in",
          

          
    },supporttab:{  
      label: "Support Network ",
      description: "Find resources and help in your community.",
      category: "Category",
      subCategories: ['Health', 'Food', 'Legal Advice', 'Emotional Support', 'Other'],
      contactSupport: "Contact Support Network",
      support_btn_title: "Support Network",
      labelcheck:"We will review the information to add it to the Support Network.",
      phone:"Crisis Line 988",
      labelphone:"Spanish support 24/7"
    }
  }
};